FROM golang:1.15

ARG ARCH
ARG OS

ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=${OS}
ENV GOARCH=${ARCH}

# project envs
ENV GOPROXY https://goproxy.io


WORKDIR /go/cache
WORKDIR /app

ADD go.mod .

# the application envs
ENV KTS_ENV_SERVICE_IP in_docker
ENV KTS_ENV_SERVICE_NAME in_docker
ENV KTS_ENV_SERVICE_NAMESPACE in_docker
ENV KTS_IS_IN_CLUSERT false
ENV KTS_USE_KUBE_FEATURE false

RUN go mod download

ADD . .

RUN go build -ldflags "-s -w" -o ./dist/app k8s-test-backend/cmd